VERSION = "2.5.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
FEDERATION_SERVER = "https://api.blocktransfer.com/federation"
ACCOUNTS = [
  "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7", # Issuer "GAQKSRI4E5643UUUMJT4RWCZVLY25TBNZXDME4WLRIF5IPOLTLV7N4N6", # Distributor
  "GD2OUJ4QKAPESM2NVGREBZTLFJYMLPCGSUHZVRMTQMF5T34UODVHPRCY", # Treasury
  "GDTCN6C4BUWRQMB7IAPXZKSBQKA22LY4I6YVBHHYCOKZCIBRRTUWCEDE"  # FAST/DWAC
]

[DOCUMENTATION]
ORG_NAME = "BlockTrans Syndicate"
ORG_DBA = "Block Transfer"
ORG_URL = "https://blocktransfer.com"
ORG_LOGO = "https://blocktransfer.com/logo.png"
ORG_DESCRIPTION = "Bringing stocks to internet speed."
ORG_PHYSICAL_ADDRESS = "99 Wall Street #4640, New York, NY 10005"
ORG_PHYSICAL_ADDRESS_ATTESTATION = "https://blocktransfer.com/compliance/proof-of-address.pdf"
ORG_PHONE_NUMBER = "+10000000000"
ORG_PHONE_NUMBER_ATTESTATION = "https://blocktransfer.com/compliance/proof-of-phone.pdf"
ORG_GITHUB = "blocktransfer"
ORG_OFFICIAL_EMAIL = "hello@blocktransfer.dev"
ORG_SUPPORT_EMAIL = "support@blocktransfer.com"
ORG_LICENSING_AUTHORITY = "US Securities and Exchange Commission"
ORG_LICENSE_TYPE = "CIK"
ORG_LICENSE_NUMBER = "1846058"

[[PRINCIPALS]]
name = "John Wooten"
github = "JFWooten4"
id_photo_hash = "0dce43292a7dd2c6ef021cca9f84330ceeec34e8587172453bc2b05f1bd13edd"
verification_photo_hash = "a3b5109c1afb0d7ce22780fc5a656bda0f24b63d4bbddcff35f44f0b8e62ff48"

[[CURRENCIES]]
attestation_of_reserve = "https://blocktransfer.com/assets/USD"
anchor_asset = "USD"
anchor_asset_type = "fiat"
code = "BTD"
conditions = "Block Transfer is not a bank and does not itself take deposits. You will not receive any interest, credit, or other earnings on the funds in your Block Transfer account. Other conditions of use apply. See https://blocktransfer.com/compliance/user"
display_decimals = 7
desc = "You can deposit US dollars as unsecured claims against Block Transfer, a Delaware corporation regulated by the SEC. We hold deposits in fungible bulk, matched 1:1 on and off Stellar. Your funds are not insured by the FDIC or SIPC. See https://blocktransfer.com/compliance/flow-of-funds"
image = "https://blocktransfer.com/imgs/usd.png"
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
is_unlimited = true
is_asset_anchored = true
name = "BT Dollars"
redemption_instructions = "Use our app to link your bank or USDC wallet."
status = "test"

[[CURRENCIES]]
attestation_of_reserve = "https://blocktransfer.com/assets/0.toml"
anchor_asset_type = "stock"
code = "DEMO"
code_template = "DEMO????????"
conditions = "Fully paid and non-assessable shares."
display_decimals = 7
desc = "Example Company is used internally for product demos and development."
image = "https://blocktransfer.com/imgs/demo.png"
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
is_unlimited = true
is_asset_anchored = true
name = "Example Company"
redemption_instructions = "Use our app to move stock to/from a legacy broker."
status = "test"

[[CURRENCIES]]
attestation_of_reserve = "https://blocktransfer.com/assets/1984803.toml"
anchor_asset_type = "stock"
code = "LAYLOR"
code_template = "LAYLOR??????"
conditions = "Fully paid and non-assessable shares."
display_decimals = 7
desc = "The content presented here is solely for informational use and should not be interpreted as an invitation to purchase securities or investment products. The utilization of tokenized shares on the Stellar blockchain is primarily to streamline recordkeeping and improve liquidity. However, this decentralized ownership data should not be construed as an endorsement or advertisement for securities offerings."
image = "https://blocktransfer.com/imgs/1984803.png"
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
is_unlimited = true
is_asset_anchored = true
name = "Laylor Corporation"
redemption_instructions = "This company is private; shares only exist here on its books."
status = "live"
